### ISSUE TITLE
missing keymaps file

### ISSUE THREAD

**Issue by ZeroChaos-** [mame82/UnifyingVulnsDisclosureRepo#4]
panic: lstat /root/keymaps: no such file or directory

it might make sense to expect this file somewhere a bit more sane? Also, where do I get this file and what is it? :-)

**Comment by mame82** [comment]
To what exactly does this question refer?

mjackit ?

**Comment by mame82** [comment]
`mjackit` references a folder with keyboard mappings and uses the US layout for one of the PoCs.

This is done here: https://github.com/mame82/UnifyingVulnsDisclosureRepo/blob/fdfed97b12371f57b85ce7fa7e16e504c0af90ce/tools/mjackit/unifying/logitacker.go#L1444

The `keymaps` folder is part of mjackit subfolder.

Unless the respective code is changed, it should reside in the same folder as a possibly compiled binary of mjackit (which seems to be `/root` in your case)

**Comment by ZeroChaos-** [comment]
Your assumptions are correct, I'll try to fix up my package.  thanks!
